name: Basecreative – Base FiveM
description: Instalação automática da base Basecreative via GitHub.
version: 1.0.0

repository:
  type: zip
  url: https://github.com/FiveCommunity/Basecreative/archive/refs/heads/main.zip

server:
  cfgPath: server.cfg

variables:
  - name: sv_licenseKey
    prompt: Insira sua chave CFX (sv_licenseKey)
    type: string

  - name: mysql_connection_string
    prompt: Digite a string de conexão MySQL (ex: mysql://root@localhost/basecreative?charset=utf8mb4)
    type: string

tasks:
  - action: extract
    src: Basecreative-main
    dest: ./

  - action: move
    src: Basecreative-main/resources
    dest: ./resources

  - action: move
    src: Basecreative-main/config
    dest: ./config

  - action: move
    src: Basecreative-main/server.cfg
    dest: ./server.cfg

  - action: ensure_latest_artifacts

  - action: replace_vars
    file: server.cfg
