name: Basecreative – Base FiveM
description: Instalação automática da base Basecreative via GitHub.
version: 1.0.0

tasks:
  - action: download_github
    src: FiveCommunity/Basecreative
    ref: main
    dest: ./basecreative
    extract: true

  - action: move_path
    src: basecreative/resources
    dest: ./resources

  - action: move_path
    src: basecreative/server.cfg
    dest: ./server.cfg

  - action: remove_path
    src: basecreative

  - action: ensure_latest_artifacts

  - action: write_file
    file: server.cfg
    append: true
    content: |
      sv_licenseKey "{{sv_licenseKey}}"
      set mysql_connection_string "{{mysql_connection_string}}"

variables:
  sv_licenseKey:
    type: string
    prompt: Insira sua key do FiveM

  mysql_connection_string:
    type: string
    prompt: String de conexão MySQL (ex: mysql://root@localhost/basecreative?charset=utf8mb4)
